// <auto-generated />
using Laundry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laundry.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20210203204915_initMig")]
    partial class initMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Laundry.Models.FirstMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientNumber")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<string>("ipAddress")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("int");

                    b.Property<string>("time")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("firstMachineOrders");
                });

            modelBuilder.Entity("Laundry.Models.SecondMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientNumber")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<string>("ipAddress")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("int");

                    b.Property<string>("time")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("secondMachineOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
