// <auto-generated />
using Laundry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Laundry.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20210130013224_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Laundry.Models.FirstMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientNumber")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("time")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("firstMachineOrders");
                });

            modelBuilder.Entity("Laundry.Models.SecondMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientNumber")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("time")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("secondMachineOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
