// <auto-generated />
using System;
using Laundry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Laundry.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Laundry.Models.FirstMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("reservationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("firstMachineOrders");
                });

            modelBuilder.Entity("Laundry.Models.SecondMachineOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("clientName")
                        .HasColumnType("text");

                    b.Property<string>("clientSurname")
                        .HasColumnType("text");

                    b.Property<int>("machineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("reservationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("secondMachineOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
